pipeline {
  agent any

  options {
    timeout(time: 2, unit: 'MINUTES')
  }

  environment {
    ARTIFACT_ID = "elbuo8/webapp:${env.BUILD_NUMBER}"
  }

  stages {
    stage('Build') {
      steps {
            sh 'ls -a'
            sh 'echo "this is a test"'
        }
      }
    }
}