FROM node:18-alpine
WORKDIR /usr/src/app
COPY ./package.json ./
RUN npm install

COPY . ./

ARG DB_USER_ENV
ARG DB_PASSWORD_ENV
ARG DB_HOST_ENV
ARG NODE_ENVIRONMENT

ENV DB_USER=$DB_USER_ENV
ENV DB_PASSWORD=$DB_PASSWORD_ENV
ENV DB_HOST=$DB_HOST_ENV
ENV NODE_ENV=$NODE_ENVIRONMENT

EXPOSE 3001
CMD [ "npm", "start" ]
