name: Run Tests

on:
  push:
    branches:
      - dev  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18  # Change to the desired Node.js version

    - name: Install dependencies
      run: npm install
      
    - name: Codeclimate
      uses: paambaati/codeclimate-action@v2.2.4
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CODECLIMATE_ACCESS_TOKEN }}
      with:
        coverageCommand: npm run test